name: Release
permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Go from the module's go.mod (recommended), with caching
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./zebrash/go.mod
          cache: true

      # Build Go -> WASM in zebrash/
      - name: Build WebAssembly (Go)
        working-directory: zebrash
        run: |
          export GOOS=js
          export GOARCH=wasm
          go build -o main.wasm .

      # Wasm_exec.js is currently bundled. Later we will use the copied handler
      # - name: Copy wasm_exec.js next to the wasm
      #   run: |
      #    cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" zebrash/wasm_exec.js#

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          registry-url: https://registry.npmjs.org

      - name: Install
        run: npm ci

      - name: Ensure package.json matches tag
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG" != "$PKG_VERSION" ]; then
            echo "Tag v$TAG does not match package.json version $PKG_VERSION"
            exit 1
          fi

      # JS Build with zebrash/main.wasm
      - name: Build
        run: npm run build

      - name: Create GitHub release (changelogithub)
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
